CoverBuilder/Controllers/PremiumController.cs
using System;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using CoverBuilder.BLL.BusinessLogics;
using CoverBuilder.BLL.Interfaces;
using CoverBuilder.Entities.Entities;
using CoverBuilder.Entities.ViewModels;
using CoverBuilder.Entities.Enums;
using Hangfire;
using System.Threading;
using System.Collections.Generic;
using CoverBuilder.Helper;
using System.IO;
using CoverBuilder.Common.Logging;
using CoverBuilder.Common.Logging.NLog;
using NLog.Config;
using System.Runtime.Caching;

namespace CoverBuilder.Controllers
{
    public partial class PremiumController : Controller
    {
        //private static readonly ILog Log = LogManager.GetLogger(typeof(PremiumController));
        private static readonly ILogger Log = new NLogger();

        public virtual JsonResult TaggedAsSynced(string referenceNumber)
        {
            ILiabilityQuotationHeaderBusinessLogic liabilityHdr = new LiabilityQuotationHeaderBusinessLogic();
            JsonResponseResult result = new JsonResponseResult();
            var updateResult = liabilityHdr.UpdateIsSynced(referenceNumber);
            if (updateResult > 0)
            {
                result.Status = "Success";
            }
            else
            {
                result.Status = "Failed";
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public virtual JsonResult ModifyStatusDecline(string userId, string status, string comments)
        {
            ILiabilityQuotationHeaderBusinessLogic liabilityHdr = new LiabilityQuotationHeaderBusinessLogic();
            JsonResponseResult result = new JsonResponseResult();
            var userInfo = liabilityHdr.GetUserInfoByReferenceNumber(userId);
            if (userInfo.Status == "Closed - Declined" || userInfo.Status == "Closed - Won" || userInfo.Status == "Closed - Lost")
            {
                result.Status = "Failed";
                result.Result = "Already Declined";
                result.Message = "Can't process request. Quote's already agreed and finalized .";
            }
            else
            {
                var updateResult = liabilityHdr.UpdateStatus(userId, status, comments);
                if (updateResult > 0)
                {
                    result.Status = "Success";
                }
                else
                {
                    result.Status = "Failed";
                }
            }


            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public virtual JsonResult ModifyStatus(string userId, string status)
        {
            ILiabilityQuotationHeaderBusinessLogic liabilityHdr = new LiabilityQuotationHeaderBusinessLogic();
            var result = liabilityHdr.UpdateStatus(userId, status);
            var response = new JsonResponseResult();
            if (result > 0)
            {
                response.Result = "Success";
            }
            else
            {
                response.Result = "Failed";
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }
        public virtual JsonResult ModifyStatusAccept(string userId, string status, string periodFrom, string periodTo)
        {
            ILiabilityQuotationHeaderBusinessLogic headerRepo = new LiabilityQuotationHeaderBusinessLogic();

            var result = headerRepo.UpdatePeriod(userId, status, periodFrom, periodTo);
            var response = new JsonResponseResult();
            if (result > 0)
            {
                response.Result = "Success";

                // INITIATE: Generation of Proposal Document
                ILiabilityInsuranceTypeBusinessLogic insuranceTypeRepo = new LiabilityInsuranceTypeBusinessLogic();
                LiabilityQuotationHeader liabilityQuotationHeader = headerRepo.GetUserInfoByReferenceNumber(userId);
                IWorkerService workerService = new WorkerService();
                List<Entities.Entities.Attachment> attachmentList = new List<Entities.Entities.Attachment>();

                // GENERATE: Proposal Document
                string proposalBytes = ReportHelper.GeneratePremiumReport(liabilityQuotationHeader.Id, "ConfirmationProposal");
                attachmentList.Add(new Entities.Entities.Attachment { File = ReportHelper.ConvertToByteArray(proposalBytes), LiabilityQuotationHeaderId = liabilityQuotationHeader.Id, Remarks = "Proposal PDF", FileName = String.Format("{0}{1}.pdf", "Proposal", DateTime.Now.ToString("yyyyMMddHHmmss")) });

                // ZOHO UPLOAD: Upload Attachments related to the Lead Record
                //workerService.UploadFilesAsync(liabilityQuotationHeader.ReferenceNumber, attachmentList);

                ObjectCache cache = MemoryCache.Default;
                var zohoAgent = new ZohoStoreV2.Service.ZohoAgentV2();
                var access_token = cache["access_token"] as string;
                if (access_token == null)
                {
                    access_token = zohoAgent.GenerateTokenv2();
                    cache.Set("access_token", access_token, DateTime.Now.AddMinutes(55));
                }

                BackgroundJob.Schedule(() => workerService.UploadFilesAsync(liabilityQuotationHeader.ReferenceNumber, attachmentList, access_token), TimeSpan.FromMinutes(1));
            }
            else
            {
                response.Result = "Failed";
            }

            return Json(response, JsonRequestBehavior.AllowGet);
        }
        public virtual JsonResult UpdateOwner(string ownerId, string referenceNum)
        {
            ILiabilityQuotationHeaderBusinessLogic headerService = new LiabilityQuotationHeaderBusinessLogic();
            var result = headerService.UpdateOwnerId(ownerId, referenceNum);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public virtual JsonResult SyncZohoUsers()
        {
            IZohoService zohoService = new ZohoService();
            IUnderwriterBusinessLogic underwriterService = new UnderwriterBusinessLogic();

            var zohoUserList = zohoService.GetZohoUsers();
            var updateStatusResult = underwriterService.SetUnderwriterInactive();
            var createResult = underwriterService.CreateUnderwriter(zohoUserList);
            return Json(updateStatusResult, JsonRequestBehavior.AllowGet);

        }
        public virtual ActionResult UserResponse(string id, int? flag)
        {
            var scheduleJobMinutes = Convert.ToInt32(ConfigurationManager.AppSettings["ScheduleJobStatusMinutes"]);
            if (Request != null && Request.QueryString.Keys.Count > 0)
            {
                ILiabilityQuotationHeaderBusinessLogic liabilityHdr = new LiabilityQuotationHeaderBusinessLogic();
                IEmailTransactionBusinessLogic transactionRepo = new EmailTransactionBusinessLogic();
                IEmailTemplateBusinessLogic templateRepo = new EmailTemplateBusinessLogic();
                EmailTransaction vm = new EmailTransaction();

                // Initial Email Info
                vm.ReferenceNumber = id;
                vm.IsActive = true;
                vm.Status = "Pending";

                var userInfo = liabilityHdr.GetUserInfoByReferenceNumber(id);
                if (userInfo.Status.Contains("Closed") || userInfo.Status.Contains("Bind Cover"))
                {
                    return Redirect("~/Home/Closed");
                }
                switch (flag)
                {
                    case (int)UserResponseEnum.Deny:
                        //ModifyStatus(id, "Closed - Lost");
                        ViewBag.ReferenceNumber = id;
                        //BackgroundJob.Enqueue(() => SyncStatus(id, DateTime.Now));

                        // Checkbox logic
                        ICheckBoxValueBusinessLogic checkboxRepo = new CheckBoxValueBusinessLogic();
                        DeclinePageRemarksViewModels checkboxModel = new DeclinePageRemarksViewModels();

                        var checkboxLookup = checkboxRepo.GetCheckBoxValue().Where(w => w.QuestionID == 1001).OrderBy(o => o.OrderID);
                        checkboxModel.CheckboxReferenceLookup = checkboxLookup.Select(x => new SelectListItem()
                        {
                            Text = x.Item,
                            Value = x.Item
                        }).ToList();

                        return View("DenyQuote", checkboxModel);

                    case (int)UserResponseEnum.Accept:
                        var model = new CoverBuilder.Entities.ViewModels.GenericInfoViewModels();
                        model.GenericInfo = userInfo;
                        model.GenericInfo.InsurancePeriodFrom = DateTime.Now;
                        model.GenericInfo.InsurancePeriodTo = DateTime.Now.AddYears(1);

                        //// Record Email Transaction
                        //vm.SentDate = DateTime.Now;
                        //vm.QuoteStatus = "Bind Cover Request";
                        //vm.TemplateId = 7; //Bind Cover Notification Email (Underwriter)
                        //vm.TemplateName = templateRepo.GetEmailTemplateByTemplateID(7).Select(s => s.Description).FirstOrDefault();

                        //transactionRepo.CreateEmailTransaction(vm);

                        //ModifyStatus(id, "Bind Cover Request");

                        //var dateTimeModel = new LiabilityQuotationHeader
                        //{
                        //    Id = model.GenericInfo.Id,
                        //    InsurancePeriodFrom = DateTime.Now,
                        //    InsurancePeriodTo = DateTime.Now.AddYears(1)
                        //};

                        //var liabilityQuoteService = new LiabilityQuotationHeaderBusinessLogic();
                        //liabilityQuoteService.UpdateInsuranceDates(dateTimeModel);

CoverBuilder/Views/Premium/AcceptQuote.cshtml
@model CoverBuilder.Entities.ViewModels.GenericInfoViewModels
@{
    ViewBag.Title = "Thank you!";
}
<div class="custom-box-container-info">

    @*Catchy Intro Text/Para*@
    <div class="user-response-page-header">
        <span>Your request to bind cover will be sent to an Underwriter to confirm via email. </span>
    </div>

    <br />
    @*Application Description*@
    <div class="user-response-page-description">
        <p>Please confirm the required Period of Insurance for the policy:</p>
    </div>

    <br />
    @using (Html.BeginForm("AcceptQuote", "Premium", FormMethod.Post))
    {
        <div class="user-response-page-insurance-period">
            <p></p>
            @*<p>@ViewBag.InsurancePeriodFrom to @ViewBag.InsurancePeriodTo</p>*@
            @Html.HiddenFor(m => m.GenericInfo.Id)
            @Html.HiddenFor(m => m.GenericInfo.LeadId)
            @Html.HiddenFor(m => m.GenericInfo.ReferenceNumber)
            <div class="period-form">
                <table>
                    <tr>
                        <td><p>From:   </p></td>
                        <td>
                            @Html.TextBoxFor(m => m.GenericInfo.InsurancePeriodFrom, new { @class = "datepickerFrom form-control", @Value = Model.GenericInfo.InsurancePeriodFrom == null ? String.Empty : Model.GenericInfo.InsurancePeriodFrom.Value.ToString("dd/MM/yyyy"), required = "required", @placeholder = "DD/MM/YYYY" })
                        </td>
                    </tr>
                    <tr>
                        <td><p>To:   </p></td>
                        <td>
                            @Html.TextBoxFor(m => m.GenericInfo.InsurancePeriodTo, new { @class = "datepickerTo form-control", @Value = Model.GenericInfo.InsurancePeriodTo == null ? String.Empty : Model.GenericInfo.InsurancePeriodTo.Value.ToString("dd/MM/yyyy"), required = "required", @placeholder = "DD/MM/YYYY"})
                            @*@Html.TextBoxFor(m => m.GenericInfo.InsurancePeriodTo, new { @class = "datepickerTo form-control", @Value = Model.GenericInfo.InsurancePeriodTo == null ? String.Empty : Model.GenericInfo.InsurancePeriodTo.Value.ToString("dd/MM/yyyy"), required = "required", @placeholder = "DD/MM/YYYY", @readonly = "readonly" })*@
                        </td>
                    </tr>
                </table>
            </div>
        </div>

        <br />
        @*Get Started Button*@
        <div class="info-page-button">
            <input type="submit" id="close" value="Submit" class="btn btn-primary" />
        </div>
        
        <br />
        <br />
        <div class="user-response-page-description-2">
            <p>Please note that no cover has been placed until you have received written confirmation from Ryno Insurance Services</p>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/datepicker")
    @Styles.Render("~/Content/datepicker")
    <script type="text/javascript">

        //Modify the background for this quotation
        $('.custom-image-background').addClass('custom-image-background-common custom-image-background-99');
        $('.navbar-inverse.navbar-fixed-top').addClass('custom-element-ninja-hide');
        $('.custom-footer-box').addClass('custom-element-ninja-hide');
        $('#myDiv').css('background-color', 'transparent');
        $('#myDiv.container.body-content').css('background', 'transparent');

        $('body').addClass('no-scroll');

        var win = this.self;
        $('#close').click(function () {
            location.href = "https://rynoinsurancebroker.com.au";
            //location.href = "about: blank";
            //win.close();
        })

        $().ready(function () {
            //Datepicker From
            $(".datepickerFrom").datepicker({
                format: 'dd/mm/yyyy',
                autoclose: true,
                todayHighlight: true,
                startDate: new Date(),
                //endDate: new Date('09/29/2018') // <-- Specific Date as Threshold
                endDate: '+59D'
            }).on('changeDate', function (selectedDate) {
                //debugger
                //September 25,2017 [Lock Date-To to minimum 1 year using Date-From]
                var aYearFromNow = new Date(selectedDate.date);
                aYearFromNow.setFullYear(aYearFromNow.getFullYear() + 1);
                //End of update

                //Format Date
                var dd = aYearFromNow.getDate();
                var mm = aYearFromNow.getMonth() + 1;
                var yyyy = aYearFromNow.getFullYear();

                if (dd < 10) { dd = '0' + dd } if (mm < 10) { mm = '0' + mm }
                var endDate = dd + '/' + mm + '/' + yyyy;

                $(".datepickerTo").val(endDate);

                // UPDATE: To-Datepicker start and end date
                //debugger
                //var convertedFromDate = new Date(moment($('.datepickerFrom').val(), 'DD-MM-YYYY').format('MM/DD/YYYY'));
                var convertedFromDate = moment($('.datepickerFrom').val(), 'DD-MM-YYYY');
                var currentDate = moment(new Date());

                var dateDiff = convertedFromDate.diff(currentDate, 'days');

                $(".datepickerTo").datepicker('setStartDate', convertedFromDate._d);
                $(".datepickerTo").datepicker('setEndDate', '+' + (dateDiff + 547) + 'D');


                //Validate
                if ($(this).val() == '') {
                    $('[data-valmsg-for="' + $(this).attr('id') + '"]').addClass('invalid-error');
                    $('[data-valmsg-for="' + $(this).attr('id') + '"]').css('display', 'block');
                    $(this).addClass('input-validation-error');
                }
                else {
                    $('[data-valmsg-for="' + $(this).attr('id') + '"]').removeClass('invalid-error');
                    $('[data-valmsg-for="' + $(this).attr('id') + '"]').css('display', 'none');
                    $(this).removeClass('input-validation-error');
                }
            });

            //Datepicker To
            //var newDate = new Date(moment($('.datepickerFrom').val(), 'DD-MM-YYYY').format('MM/DD/YYYY'));

            $(".datepickerTo").datepicker({
                format: 'dd/mm/yyyy',
                autoclose: true,
                todayHighlight: true,
                //startDate: new Date(),
                startDate: $('.datepickerFrom').val(),
                //endDate: '+' + (new Date(moment($('.datepickerFrom').val(), 'DD-MM-YYYY').format('MM/DD/YYYY')).getDate() + 547).toString() + 'D'
                endDate: '+547D',
            }).on('changeDate', function (selectedDate) {
                //debugger
                //$('#GenericInfo_InsurancePeriodTo').val(selectedDate.date.toLocaleDateString());
                if (selectedDate.date < $('.datepickerFrom').val()) {
                    $(this).datepicker('setDate', null);
                }
            });

        })

    </script>
}

CoverBuilder/Views/Premium/DenyQuote.cshtml
@model CoverBuilder.Entities.ViewModels.DeclinePageRemarksViewModels

@{
    ViewBag.Title = "Thank you!";
}

<div class="custom-box-container-info">

    @*Catchy Intro Text/Para*@
    <div class="user-response-page-header">
        <span>We are sorry to hear that you do not wish to proceed with the quotation.</span>
    </div>

    <br />
    @*Application Description*@
    <div class="user-response-page-description">
        <span>Your feedback on our terms is greatly appreciated</span>
        <br /><br />
        @*@Html.TextArea("DenyComment", null, new { @class = "comment-box", @id = "DenyComment", placeholder = "Enter your feedbacks here..." })*@

    </div>
    <div class="deny-comments-section">
        @for (int i = 0; i < Model.CheckboxReferenceLookup.Count; i++)
        {
            @Html.HiddenFor(m => m.CheckboxReferenceLookup[i].Text, new { @id = "DenyComment" })
            @Html.HiddenFor(m => m.CheckboxReferenceLookup[i].Value, new { @id = "DenyComment" })
            if (Model.CheckboxReferenceLookup[i].Text.TrimEnd().ToUpper() == "OTHER")
            {
                @Html.CheckBoxFor(m => m.CheckboxReferenceLookup[i].Selected, new { @id = "DenyComment", @class = "chk-others", onclick = "javascript:CBClickOther(checked);" })
                <text>
                    @Html.TextBoxFor(m => m.CheckboxReferenceLookup[i].Value, null, new { @class = "otherDenyComment", placeholder = "Other", onclick = "javascript:TextClickOther();", @Value = "" })

                </Text>
            }
            else
            {
                @Html.CheckBoxFor(m => m.CheckboxReferenceLookup[i].Selected, new { @id = "DenyComment" })
                <span>@Model.CheckboxReferenceLookup[i].Text</span>
            }
            <br />
        }
        @Html.ValidationMessage("CheckboxValidation", "Please check atleast one item!", new { @class = "text-danger validationMessage" })
    </div>

    <br /><br />
    @*Submit and Close*@
    <div class="info-page-button">
        <input type="button" id="close" value="Submit" class="btn btn-primary" />
    </div>

</div>

@section Scripts {

    <script type="text/javascript">
        var referenceNumber = '@(ViewBag.ReferenceNumber)';
        //Modify the background for this quotation
        $('.custom-image-background').addClass('custom-image-background-common custom-image-background-99');
        $('.navbar-inverse.navbar-fixed-top').addClass('custom-element-ninja-hide');
        $('.custom-footer-box').addClass('custom-element-ninja-hide');
        $('#myDiv').css('background-color', 'transparent');
        $('#myDiv.container.body-content').css('background', 'transparent');

        $('body').addClass('no-scroll');

        var win = this.self;
        $('#close').click(function () {
            var validCheckbox = ValidateCheckbox();
            if (validCheckbox) {
                var validOtherField = ValidateOtherField();
                if (validOtherField) {
                    // Concatenate Checkbox Values
                    var concatCheckBoxValues = "";
                    var length = $('[type="checkbox"][name^="CheckboxReferenceLookup"]').length;

                    for (var ctr = 0; ctr < length; ctr++) {
                        if ($('[type="checkbox"][name^="CheckboxReferenceLookup"]')[ctr].checked) {
                            var item = $('[type="hidden"][name="CheckboxReferenceLookup[' + ctr + '].Text"]').val();
                            if (item != "Other")
                                concatCheckBoxValues = item + " | " + concatCheckBoxValues;
                        }
                    }

                    // Add Other Decline Reasons
                    var othersDenyComment = $('.otherDenyComment').val();
                    if (othersDenyComment != '')
                        concatCheckBoxValues = concatCheckBoxValues + othersDenyComment

                    //var remarksVal = $('#DenyComment').val();
                    var remarksVal = concatCheckBoxValues;

                    $.ajax({
                        type: "POST",
                        url: "@Url.Action("SaveRemarks", "Premium")",
                        data: { referenceId: referenceNumber, remarks: remarksVal },
                    dataType: 'json',
                    success: function (response) {
                        window.location.href = response.Url;
                    },
                    error: function () {
                    }
                });
                }
                
            }


            //location.href = "about: blank";
            //win.close();
        })
        $('[type="checkbox"]').on('change', function () {
            ValidateCheckbox();
        });
        $('.otherDenyComment').on('blur', function () {
            debugger
            ValidateOtherField();
        });
        function ValidateCheckbox() {
            var valid = true
            var ctr = 0
            $('.deny-comments-section').each(function () {
                var checked = $(this).find('input[type="checkbox"]:checked');
                if (checked.length === 0) {
                    $(this).addClass('ValidateContainer');
                    $(this).find('.validationMessage').css("display", "block");
                    $(this).find('.validationMessage').text("Please check atleast one item!");
                    ctr++;
                } else {
                    $(this).removeClass('ValidateContainer');
                    $(this).find('.validationMessage').css("display", "none");

                }
            });
            if (ctr > 0) {
                valid = false;
            }
            return valid;
        };
        function ValidateOtherField() {
            debugger
            var valid = true;
            var ctr = 0;
            var otherChecked = $('.chk-others:checked').length;
            $('.otherDenyComment').each(function () {
                if ($(this).val() == '' && otherChecked !== 0 ) {
                    $('.validationMessage').css("display", "block");
                    $('.validationMessage').text("Please provide details!");
                    ctr++;
                } else {
                    $('.validationMessage').css("display", "none");
                }
            });
            if (ctr > 0) {
                valid = false;
            }
            return valid;
        };
        function CBClickOther(value) {
            if (value) {
                $('.otherDenyComment').prop('required');
                $('#Q132CBValueTBoxwb11').focus();
            }
            else {
                $('.otherDenyComment').val('');
            }
        }
        function TextClickOther() {
            $($('[type="checkbox"].chk-others')).prop('checked', true);
        }

    </script>

}

CoverBuilder/Views/Premium/EmailQuote.cshtml
@{
    ViewBag.Title = "Quote Email Sent!";
}

<div class="custom-box-container-info">

    @*Catchy Intro Text/Para*@
    <div class="info-page-header">
        <span>Quote Email Requested!</span>
    </div>

    <br /><br /><br />
    @*Get Started Button*@
    <div class="info-page-button">
        <input type="button" id="close" value="Close" class="btn btn-primary" />
    </div>

</div>

@section Scripts {

    <script type="text/javascript">

        //Modify the background for this quotation
        $('.custom-image-background').addClass('custom-image-background-common custom-image-background-99');
        $('.navbar-inverse.navbar-fixed-top').addClass('custom-element-ninja-hide');
        $('.custom-footer-box').addClass('custom-element-ninja-hide');
        $('#myDiv').css('background-color', 'transparent');
        $('#myDiv.container.body-content').css('background', 'transparent');

        $('body').addClass('no-scroll');

        var win = this.self;
        $('#close').click(function () {
            location.href = "http://www.google.com";
            //location.href = "about: blank";
            //win.close();
        })

    </script>

}

CoverBuilder/Views/Premium/Premium.cshtml
@model CoverBuilder.Entities.ViewModels.LiabilityInsuranceTypeViewModels

@{
    ViewBag.Title = "My Premium";
    //int UserID = ((int)Session["GenericUserID"]);
    //var UserID = Request.Url.Segments[3];
    var UserID = Request.Url.Segments.Last();
}

<br />
<h2>My Premium</h2>

<br />
<div class="custom-content-desc">
    <p>Thank you for getting a quotation with us. Below are the details of your monthly premium</p>
</div>

<br />
<div class="col-lg-12">
    <div class="custom-form-box">

        <h3>Premium Details</h3>
        <div class="premium-details-box">
            <table class="w-100">
                <tr>
                    <td class="w-40"><p>Reference ID</p></td>
                    <td class="w-60">@UserID</td>
                </tr>

                <tr>
                    <td class="w-40"><p>Brokerage Name</p></td>
                    <td class="w-60">@Session["GenericUserBrokerageName"]</td>
                </tr>

                <tr>
                    <td><p>Name</p></td>
                    <td>@Session["GenericUserName"] </td>
                </tr>

                <tr>
                    <td><p>Email</p></td>
                    <td>@Session["GenericUserEmail"]</td>
                </tr>

                <tr>
                    <td><p>Contact Number</p></td>
                    <td>@Session["GenericUserPhone"]</td>
                </tr>

                <tr>
                    <td><p>Full Insured Name</p></td>
                    <td>@Session["GenericInsuredName"]</td>
                </tr>

                <tr>
                    <td><p>Situation</p></td>
                    <td>@Session["GenericState"]</td>
                </tr>

                <tr>
                    <td><p>Liability Limit</p></td>
                    <td>@Session["GenericLiabilityLimit"]</td>
                </tr>

            </table>
        </div>

        <div class="premium-calc-box">

            <table class="w-100">
                <tr>
                    <td><p>Base Premium: </p></td>
                    <td>@string.Format("{0:N}", Session["SessionBasePremium"])</td>
                </tr>

                <tr>
                    <td><p>Discounts: </p></td>
                    <td>@(Convert.ToDecimal(Session["SessionAccumulatedDiscount"]) * 100) %</td>
                </tr>

                <tr>
                    <td><p>GST: </p></td>
                    <td>@(Convert.ToDecimal(Session["SessionGST"]) * 100) %</td>
                </tr>

                <tr>
                    <td><p>Stamp Duty: </p></td>
                    <td>@(Convert.ToDecimal(Session["GenericStateTaxRate"]) * 100) %</td>
                </tr>

                <tr>
                    <td><p>U/W Fee: </p></td>
                    <td>@string.Format("{0:N}", Session["SessionUWFee"])</td>
                </tr>

                <tr>
                    <td><p>GST on U/W Fee: </p></td>
                    <td>@(Convert.ToDecimal(Session["SessionUWFeeGST"]) * 100) %</td>
                </tr>

                <tr>
                    <td><p>Excess Fees: </p></td>
                    <td>@string.Format("{0:N}", Session["SessionExcesses"])</td>
                </tr>

                <tr>
                    @*<td class="premium-value"><span style="font-size:50px">@string.Format("{0:N}", ViewBag.FinalPremium)</span><span>per month</span></td>*@
                </tr>

            </table>
            <div class="premium-value"><span style="font-size:50px">@string.Format("{0:N}", ViewBag.FinalPremium)</span><span>per month</span></div>
        </div>

        <br />
        <input type="submit" id="btnExit" value="Modify Personal Details" class="btn btn-primary" />
        <br />
        <div>
            <input type="submit" id="btnPDF" value="Deny Quote" class="btn btn-primary" />
            <input type="submit" id="btnPDF" value="Accept Quote" class="btn btn-primary" />
        </div>

    </div>
</div>





@section Scripts {

    <script type="text/javascript">

        //Modify the background for this page
        $('.custom-image-background').addClass('custom-image-background-common custom-image-background-98');

    </script>

}

CoverBuilder/Views/Premium/Referral.cshtml
@{
    ViewBag.Title = "Referral";
}

<h2>Referral</h2>